const PREFIX="movie-mentor:pending-turn:v1:";
const clean=value=>typeof value==="string"?value.trim():"";
function fail(code,message,extras={}){const error=new Error(message);error.code=code;Object.assign(error,extras);throw error;}
function key({projectId,creatorSessionId}={}){const project=clean(projectId),session=clean(creatorSessionId);const identity=project||session;if(!identity)fail("MOVIE_MENTOR_TURN_IDENTITY_REQUIRED","Movie Mentor needs a durable identity before a turn can be sent.");return `${PREFIX}${project?`project:${project}`:`session:${session}`}`;}
function readPendingTurn({identity,storage}={}){if(!storage||typeof storage.getItem!=="function")return null;try{const value=JSON.parse(storage.getItem(key(identity))||"null");const creatorTurnId=clean(value?.creatorTurnId),message=clean(value?.message);return creatorTurnId&&message?{creatorTurnId,message}:null;}catch{return null;}}
function mintCreatorTurnId(cryptoImpl=globalThis?.crypto){if(typeof cryptoImpl?.randomUUID!=="function")fail("MOVIE_MENTOR_CREATOR_TURN_ID_UNAVAILABLE","Movie Mentor cannot create a stable creator turn identity on this device.");return cryptoImpl.randomUUID();}
function resolvePendingTurn({identity,message,storage,cryptoImpl=globalThis?.crypto}={}){const text=clean(message);const existing=readPendingTurn({identity,storage});if(existing){if(existing.message!==text)fail("MOVIE_MENTOR_PENDING_TURN_UNRESOLVED","A previous Movie Mentor turn still has an uncertain outcome. Retry that turn before sending a different message.",{creatorTurnId:existing.creatorTurnId});return existing;}if(!storage||typeof storage.setItem!=="function")fail("MOVIE_MENTOR_CREATOR_TURN_STORAGE_REQUIRED","Movie Mentor requires durable client storage before a live turn can be sent.");const pending={creatorTurnId:mintCreatorTurnId(cryptoImpl),message:text};storage.setItem(key(identity),JSON.stringify(pending));return pending;}
function clearPendingTurn({identity,creatorTurnId,storage}={}){if(!storage||typeof storage.removeItem!=="function")return;const pending=readPendingTurn({identity,storage});if(pending?.creatorTurnId===clean(creatorTurnId))storage.removeItem(key(identity));}
export{readPendingTurn,resolvePendingTurn,clearPendingTurn};
