const MOVIE_MENTOR_COMMERCIAL_CLIENT_VERSION="1.1.0";
function clean(value){return typeof value==="string"?value.trim():"";}
function apiBase(){return clean(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function error(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);return e;}
function bearer(token){const value=clean(token);if(!value)throw error("MOVIE_MENTOR_COMMERCIAL_AUTH_REQUIRED","Sign in before starting a Movie Mentor purchase.");return `Bearer ${value}`;}
async function json(response){return response.json().catch(()=>({}));}
async function post(path,body,{token,fetchImpl=globalThis?.fetch}={}){if(typeof fetchImpl!=="function")throw error("MOVIE_MENTOR_COMMERCIAL_FETCH_UNAVAILABLE","Movie Mentor cannot reach the commercial gateway.");const response=await fetchImpl(`${apiBase()}/api/movie-mentor/commercial${path}`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":bearer(token)},body:JSON.stringify(body)});const payload=await json(response);if(!response.ok||payload?.success!==true)throw error(clean(payload?.code)||"MOVIE_MENTOR_COMMERCIAL_REQUEST_FAILED",clean(payload?.message)||"Movie Mentor could not safely complete that commercial request.",{status:response.status});return payload;}
async function createMovieMentorPurchaseIntent({packageId,token,fetchImpl}={}){const selected=clean(packageId);if(!selected)throw error("MOVIE_MENTOR_COMMERCIAL_PACKAGE_REQUIRED","Choose a Movie Mentor package first.");const payload=await post("/purchase-intents",{packageId:selected},{token,fetchImpl});const intent=payload?.intent;const commercialIntentId=clean(intent?.commercialIntentId);if(!commercialIntentId)throw error("MOVIE_MENTOR_COMMERCIAL_INTENT_INVALID","Movie Mentor did not return a durable commercial intent.");return{...intent,commercialIntentId};}
async function createMovieMentorCheckout({commercialIntentId,token,fetchImpl}={}){const id=clean(commercialIntentId);if(!id)throw error("MOVIE_MENTOR_COMMERCIAL_INTENT_REQUIRED","A durable Movie Mentor commercial intent is required before checkout.");const payload=await post("/checkout",{commercialIntentId:id},{token,fetchImpl});const checkout=payload?.checkout;const checkoutUrl=clean(checkout?.checkoutUrl);if(!checkoutUrl)throw error("MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INVALID","Movie Mentor did not return an authorized checkout destination.");return{...checkout,checkoutUrl};}
async function beginMovieMentorPurchase({packageId,token,fetchImpl,navigate=(url)=>globalThis?.location?.assign?.(url)}={}){const intent=await createMovieMentorPurchaseIntent({packageId,token,fetchImpl});const checkout=await createMovieMentorCheckout({commercialIntentId:intent.commercialIntentId,token,fetchImpl});if(typeof navigate!=="function")throw error("MOVIE_MENTOR_COMMERCIAL_NAVIGATION_UNAVAILABLE","Checkout is authorized but this client cannot navigate to the provider.");navigate(checkout.checkoutUrl);return{intent,checkout};}
export{MOVIE_MENTOR_COMMERCIAL_CLIENT_VERSION,createMovieMentorPurchaseIntent,createMovieMentorCheckout,beginMovieMentorPurchase};
export default beginMovieMentorPurchase;
