const MOVIE_MENTOR_DURABLE_STATE_SYNC_VERSION="1.0.0";
const REVISION_KEY_PREFIX="iband.movie-mentor.durable-revision";
function s(v){return typeof v==="string"?v.trim():"";}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function apiBase(){return s(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function revisionKey(projectId,creatorSessionId){return `${REVISION_KEY_PREFIX}:${s(projectId)||`session:${s(creatorSessionId)}`}`;}
function getExpectedRevision({projectId,creatorSessionId,storage=globalThis?.localStorage}={}){try{const value=Number(storage?.getItem?.(revisionKey(projectId,creatorSessionId)));return Number.isSafeInteger(value)&&value>=0?value:0;}catch{return 0;}}
function rememberRevision({projectId,creatorSessionId,revision,storage=globalThis?.localStorage}={}){if(!Number.isSafeInteger(revision)||revision<0)return;try{storage?.setItem?.(revisionKey(projectId,creatorSessionId),String(revision));}catch{}}
function projectMemoryContext(memoryState,projectId){const pid=s(projectId);const relevant=(items=[])=>items.filter(item=>{const direct=s(item?.projectId||item?.relatedProjectId||item?.metadata?.projectId);const related=Array.isArray(item?.relatedProjectIds)?item.relatedProjectIds.map(s):[];return !direct&&!related.length||direct===pid||related.includes(pid);});return{creatorProfile:clone(memoryState?.creatorProfile||null),ideas:clone(relevant(memoryState?.ideas||[])),projectMemories:clone(relevant(memoryState?.projectMemories||[])),sessionHandoffs:clone(relevant(memoryState?.sessionHandoffs||[])),conversations:clone(relevant(memoryState?.conversations||[])),observations:clone(relevant(memoryState?.observations||[])),patterns:clone(relevant(memoryState?.patterns||[])),milestones:clone(relevant(memoryState?.milestones||[])),reflections:clone(relevant(memoryState?.reflections||[])),deferredMemories:clone(relevant(memoryState?.deferredMemories||[]))};}
function creatorConfirmedContext(memoryState,projectId){const pid=s(projectId);const project=(memoryState?.projects||[]).find(p=>s(p?.id||p?.projectId)===pid)||null;return[{key:"creatorProfile",value:clone(memoryState?.creatorProfile||null),source:"creator-memory",certainty:"confirmed"},{key:"project",value:clone(project),source:"creator-memory",certainty:"confirmed"}].filter(x=>x.value!==null);}
async function syncMovieMentorDurableState({projectId,creatorSessionId=null,memoryState,source="creator-memory",fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage}={}){const pid=s(projectId),sid=s(creatorSessionId);if(!pid&&!sid)throw new Error("Movie Mentor durable sync requires projectId or creatorSessionId.");if(!memoryState||typeof memoryState!=="object")throw new Error("Movie Mentor durable sync requires CreatorMemory state.");if(typeof fetchImpl!=="function")throw new Error("Movie Mentor durable sync requires fetch.");const expectedRevision=getExpectedRevision({projectId:pid,creatorSessionId:sid,storage});const response=await fetchImpl(`${apiBase()}/api/movie-mentor/state/sync`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:pid||null,creatorSessionId:sid||null,source,expectedRevision,state:{creatorConfirmedContext:creatorConfirmedContext(memoryState,pid),projectJourney:clone(memoryState?.journey||null),memoryContext:projectMemoryContext(memoryState,pid)}})});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload?.message||"Movie Mentor durable state sync failed.");error.code=payload?.code||"MOVIE_MENTOR_DURABLE_STATE_SYNC_FAILED";error.status=response.status;throw error;}rememberRevision({projectId:pid,creatorSessionId:sid,revision:payload?.state?.revision,storage});return payload;}
export{MOVIE_MENTOR_DURABLE_STATE_SYNC_VERSION,getExpectedRevision,rememberRevision,projectMemoryContext,creatorConfirmedContext,syncMovieMentorDurableState};
export default syncMovieMentorDurableState;
