import {
  flushMovieMentorDurableStateSync,
  getDurableSyncStatus,
  rememberRevision,
} from "./MovieMentorDurableStateSync.js";

const MOVIE_MENTOR_TURN_CLIENT_VERSION = "1.3.0";
function cleanString(value){return typeof value==="string"?value.trim():"";}
function clone(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch{return value;}}
function safeRevision(value){const number=Number(value);return Number.isSafeInteger(number)&&number>=0?number:null;}
function apiBase(){return cleanString(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function createTurnError(code,message,extras={}){const error=new Error(message);error.code=code;Object.assign(error,extras);return error;}
function resolveIdentity({projectId,creatorSessionId}={}){const project=cleanString(projectId),session=cleanString(creatorSessionId);if(!project&&!session)throw createTurnError("MOVIE_MENTOR_TURN_IDENTITY_REQUIRED","Movie Mentor needs a projectId or creatorSessionId before a live turn can run.");return{projectId:project||null,creatorSessionId:session||null};}
function assertDurableRealityAcknowledged(status){if(!status||status.status==="acknowledged")return;if(["queued","syncing","retry-pending","conflict-pending"].includes(status.status))throw createTurnError("MOVIE_MENTOR_DURABLE_REALITY_NOT_ACKNOWLEDGED","The creator's latest durable reality has not been acknowledged yet, so Movie Mentor will not reason against an older snapshot.",{durableSyncStatus:status});}
function normalisePostCommitCreatorAuthority(input,turnContextProof=null){if(input==null)return null;if(!input||typeof input!=="object")throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Movie Mentor returned malformed post-commit creator authority.");const revision=safeRevision(input.revision),priorRevision=safeRevision(turnContextProof?.revision);const canonicalTruth=Array.isArray(input.currentCreatorTruth)?input.currentCreatorTruth:Array.isArray(input.creatorConfirmedContext)?input.creatorConfirmedContext:null;const creatorConfirmedContext=canonicalTruth?clone(canonicalTruth):null;if(revision===null||creatorConfirmedContext===null)throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Movie Mentor returned incomplete post-commit creator authority.");if(priorRevision!==null&&revision<=priorRevision)throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_NOT_NEWER","Post-commit creator authority must be newer than the turn snapshot it supersedes.",{priorRevision,revision});return{...clone(input),revision,currentCreatorTruth:clone(creatorConfirmedContext),creatorConfirmedContext};}
async function resolveAuthToken(getAuthToken){if(typeof getAuthToken!=="function")throw createTurnError("MOVIE_MENTOR_TURN_AUTH_REQUIRED","Movie Mentor requires an authenticated creator session before a live turn can run.");let token;try{token=await getAuthToken();}catch(cause){if(cause?.code)throw cause;throw createTurnError("MOVIE_MENTOR_TURN_AUTH_TOKEN_FAILED","Movie Mentor could not obtain a current authenticated creator token.",{cause});}const value=cleanString(token);if(!value)throw createTurnError("MOVIE_MENTOR_TURN_AUTH_TOKEN_MISSING","Movie Mentor did not receive an authenticated creator token.");return value;}
async function requestMovieMentorTurn({message,projectId=null,creatorSessionId=null,getAuthToken,fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage}={}){const creatorMessage=cleanString(message);if(!creatorMessage)throw createTurnError("MOVIE_MENTOR_TURN_MESSAGE_REQUIRED","A creator message is required for a live Movie Mentor turn.");if(typeof fetchImpl!=="function")throw createTurnError("MOVIE_MENTOR_TURN_FETCH_UNAVAILABLE","Movie Mentor cannot reach the backend turn gateway because fetch is unavailable.");const identity=resolveIdentity({projectId,creatorSessionId});await flushMovieMentorDurableStateSync({...identity,fetchImpl,storage});const durableStatus=getDurableSyncStatus({...identity,storage});assertDurableRealityAcknowledged(durableStatus);const token=await resolveAuthToken(getAuthToken);const response=await fetchImpl(`${apiBase()}/api/movie-mentor/turn`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify({...identity,message:creatorMessage})});const payload=await response.json().catch(()=>({}));if(!response.ok||payload?.success!==true)throw createTurnError(cleanString(payload?.code)||"MOVIE_MENTOR_LIVE_TURN_FAILED",cleanString(payload?.message)||"The authoritative Movie Mentor turn did not complete.",{status:response.status,validationIssues:Array.isArray(payload?.validationIssues)?payload.validationIssues:[]});const text=cleanString(payload?.text);if(!text)throw createTurnError("MOVIE_MENTOR_LIVE_TURN_EMPTY_RESPONSE","The authoritative Movie Mentor turn returned no creator-facing response.");const postCommitCreatorAuthority=normalisePostCommitCreatorAuthority(payload?.postCommitCreatorAuthority,payload?.turnContextProof);if(postCommitCreatorAuthority)rememberRevision({...identity,revision:postCommitCreatorAuthority.revision,storage});return{...payload,text,postCommitCreatorAuthority,durableSyncStatus:durableStatus,metadata:{...(payload?.metadata||{}),turnClientVersion:MOVIE_MENTOR_TURN_CLIENT_VERSION,liveBackendTurn:true,authenticatedCreatorTransport:true,localResponseGeneratorUsed:false,postCommitCreatorAuthorityTransported:postCommitCreatorAuthority!==null,postCommitCreatorAuthority:clone(postCommitCreatorAuthority)}};}
export{MOVIE_MENTOR_TURN_CLIENT_VERSION,resolveIdentity,assertDurableRealityAcknowledged,normalisePostCommitCreatorAuthority,resolveAuthToken,requestMovieMentorTurn};
export default requestMovieMentorTurn;
