import {
  flushMovieMentorDurableStateSync,
  getDurableSyncStatus,
  rememberRevision,
} from "./MovieMentorDurableStateSync.js";
import { getMovieMentorCreatorAuthToken } from "./MovieMentorCreatorAuthenticationTransport.js";
import { establishMovieMentorProject } from "./MovieMentorProjectEstablishmentAuthority.js";
import { resolvePendingTurn } from "./MovieMentorTurnIdentity.js";

const MOVIE_MENTOR_TURN_CLIENT_VERSION = "1.7.0";
const localTurnLockTails = new Map();
function cleanString(value){return typeof value==="string"?value.trim():"";}
function clone(value){if(value===undefined)return undefined;try{return JSON.parse(JSON.stringify(value));}catch{return value;}}
function safeRevision(value){const number=Number(value);return Number.isSafeInteger(number)&&number>=0?number:null;}
function apiBase(){return cleanString(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function createTurnError(code,message,extras={}){const error=new Error(message);error.code=code;Object.assign(error,extras);return error;}
function resolveIdentity({projectId,creatorSessionId}={}){const project=cleanString(projectId),session=cleanString(creatorSessionId);if(!project&&!session)throw createTurnError("MOVIE_MENTOR_TURN_IDENTITY_REQUIRED","Movie Mentor needs a projectId or creatorSessionId before a live turn can run.");return{projectId:project||null,creatorSessionId:session||null};}
function pendingTurnLockName(identity={}){const resolved=resolveIdentity(identity);return `iband.movie-mentor.pending-turn:${resolved.projectId?`project:${resolved.projectId}`:`session:${resolved.creatorSessionId}`}`;}
function localLockManager(){return{request(name,operation){const prior=localTurnLockTails.get(name)||Promise.resolve();const current=prior.catch(()=>{}).then(()=>operation());const tail=current.catch(()=>{});localTurnLockTails.set(name,tail);return current.finally(()=>{if(localTurnLockTails.get(name)===tail)localTurnLockTails.delete(name);});}};}
async function withPendingTurnLock({identity,lockManager=globalThis?.navigator?.locks,operation}={}){if(typeof operation!=="function")throw createTurnError("MOVIE_MENTOR_TURN_LOCK_OPERATION_REQUIRED","Movie Mentor pending-turn serialization requires an operation.");let manager=lockManager;const browserRuntime=typeof globalThis?.window!=="undefined"||typeof globalThis?.document!=="undefined";if((!manager||typeof manager.request!=="function")&&!browserRuntime)manager=localLockManager();if(!manager||typeof manager.request!=="function")throw createTurnError("MOVIE_MENTOR_TURN_LOCK_UNAVAILABLE","Movie Mentor cannot safely start a live turn because this browser cannot serialize same-project pending-turn ownership across tabs.");return manager.request(pendingTurnLockName(identity),operation);}
function assertDurableRealityAcknowledged(status){if(!status||status.status==="acknowledged")return;if(["queued","syncing","retry-pending","conflict-pending"].includes(status.status))throw createTurnError("MOVIE_MENTOR_DURABLE_REALITY_NOT_ACKNOWLEDGED","The creator's latest durable reality has not been acknowledged yet, so Movie Mentor will not reason against an older snapshot.",{durableSyncStatus:status});}
function normalisePostCommitCreatorAuthority(input,turnContextProof=null){if(input==null)return null;if(!input||typeof input!=="object")throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Movie Mentor returned malformed post-commit creator authority.");const revision=safeRevision(input.revision),priorRevision=safeRevision(turnContextProof?.revision);const canonicalTruth=Array.isArray(input.currentCreatorTruth)?input.currentCreatorTruth:Array.isArray(input.creatorConfirmedContext)?input.creatorConfirmedContext:null;const creatorConfirmedContext=canonicalTruth?clone(canonicalTruth):null;if(revision===null||creatorConfirmedContext===null)throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_INVALID","Movie Mentor returned incomplete post-commit creator authority.");if(priorRevision!==null&&revision<=priorRevision)throw createTurnError("MOVIE_MENTOR_POST_COMMIT_AUTHORITY_NOT_NEWER","Post-commit creator authority must be newer than the turn snapshot it supersedes.",{priorRevision,revision});return{...clone(input),revision,currentCreatorTruth:clone(creatorConfirmedContext),creatorConfirmedContext};}
async function resolveAuthToken(getAuthToken=getMovieMentorCreatorAuthToken){if(typeof getAuthToken!=="function")throw createTurnError("MOVIE_MENTOR_TURN_AUTH_REQUIRED","Movie Mentor requires an authenticated creator session before a live turn can run.");let token;try{token=await getAuthToken();}catch(cause){if(cause?.code)throw cause;throw createTurnError("MOVIE_MENTOR_TURN_AUTH_TOKEN_FAILED","Movie Mentor could not obtain a current authenticated creator token.",{cause});}const value=cleanString(token);if(!value)throw createTurnError("MOVIE_MENTOR_TURN_AUTH_TOKEN_MISSING","Movie Mentor did not receive an authenticated creator token.");return value;}
async function requestMovieMentorTurn({message,projectId=null,projectIdentity=null,creatorSessionId=null,getAuthToken=getMovieMentorCreatorAuthToken,fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,lockManager=globalThis?.navigator?.locks}={}){const creatorMessage=cleanString(message);if(!creatorMessage)throw createTurnError("MOVIE_MENTOR_TURN_MESSAGE_REQUIRED","A creator message is required for a live Movie Mentor turn.");if(typeof fetchImpl!=="function")throw createTurnError("MOVIE_MENTOR_TURN_FETCH_UNAVAILABLE","Movie Mentor cannot reach the backend turn gateway because fetch is unavailable.");const identity=resolveIdentity({projectId,creatorSessionId});await establishMovieMentorProject({projectId:identity.projectId,projectIdentity,fetchImpl,getAuthToken});await flushMovieMentorDurableStateSync({...identity,fetchImpl,storage});const durableStatus=getDurableSyncStatus({...identity,storage});assertDurableRealityAcknowledged(durableStatus);const token=await resolveAuthToken(getAuthToken);return withPendingTurnLock({identity,lockManager,operation:async()=>{const pending=resolvePendingTurn({identity,message:creatorMessage,storage});const creatorTurnId=pending.creatorTurnId;const response=await fetchImpl(`${apiBase()}/api/movie-mentor/turn`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify({...identity,creatorTurnId,message:creatorMessage})});const payload=await response.json().catch(()=>({}));if(!response.ok||payload?.success!==true)throw createTurnError(cleanString(payload?.code)||"MOVIE_MENTOR_LIVE_TURN_FAILED",cleanString(payload?.message)||"The authoritative Movie Mentor turn did not complete.",{status:response.status,creatorTurnId,validationIssues:Array.isArray(payload?.validationIssues)?payload.validationIssues:[]});const text=cleanString(payload?.text);if(!text)throw createTurnError("MOVIE_MENTOR_LIVE_TURN_EMPTY_RESPONSE","The authoritative Movie Mentor turn returned no creator-facing response.",{creatorTurnId});const postCommitCreatorAuthority=normalisePostCommitCreatorAuthority(payload?.postCommitCreatorAuthority,payload?.turnContextProof);if(postCommitCreatorAuthority)rememberRevision({...identity,revision:postCommitCreatorAuthority.revision,storage});return{...payload,text,postCommitCreatorAuthority,durableSyncStatus:durableStatus,metadata:{...(payload?.metadata||{}),turnClientVersion:MOVIE_MENTOR_TURN_CLIENT_VERSION,creatorTurnId,liveBackendTurn:true,authenticatedCreatorTransport:true,stableCreatorTurnTransport:true,sameProjectPendingTurnSerialized:true,pendingTurnRetirementDeferred:true,localResponseGeneratorUsed:false,postCommitCreatorAuthorityTransported:postCommitCreatorAuthority!==null,postCommitCreatorAuthority:clone(postCommitCreatorAuthority)}};}});}
export{MOVIE_MENTOR_TURN_CLIENT_VERSION,resolveIdentity,pendingTurnLockName,withPendingTurnLock,assertDurableRealityAcknowledged,normalisePostCommitCreatorAuthority,resolveAuthToken,requestMovieMentorTurn};
export default requestMovieMentorTurn;
