import { getMovieMentorCreatorAuthToken } from "./MovieMentorCreatorAuthenticationTransport.js";

const MOVIE_MENTOR_COMMERCIAL_CLIENT_VERSION="1.3.1";
function clean(value){return typeof value==="string"?value.trim():"";}
function apiBase(){return clean(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function error(code,message,extras={}){const e=new Error(message);e.code=code;Object.assign(e,extras);return e;}
function bearer(token){const value=clean(token);if(!value)throw error("MOVIE_MENTOR_COMMERCIAL_AUTH_REQUIRED","Sign in before using Movie Mentor commercial access.");return `Bearer ${value}`;}
async function resolveToken({token,getAuthToken=getMovieMentorCreatorAuthToken}={}){const supplied=clean(token);if(supplied)return supplied;if(typeof getAuthToken!=="function")throw error("MOVIE_MENTOR_COMMERCIAL_AUTH_REQUIRED","Sign in before using Movie Mentor commercial access.");let resolved;try{resolved=await getAuthToken();}catch(cause){if(cause?.code)throw cause;throw error("MOVIE_MENTOR_COMMERCIAL_AUTH_TOKEN_FAILED","Movie Mentor could not obtain a current authenticated creator token.",{cause});}const value=clean(resolved);if(!value)throw error("MOVIE_MENTOR_COMMERCIAL_AUTH_REQUIRED","Sign in before using Movie Mentor commercial access.");return value;}
async function json(response){return response.json().catch(()=>({}));}
async function request(path,{method="GET",body,token:inputToken,getAuthToken,fetchImpl=globalThis?.fetch}={}){if(typeof fetchImpl!=="function")throw error("MOVIE_MENTOR_COMMERCIAL_FETCH_UNAVAILABLE","Movie Mentor cannot reach the commercial gateway.");const token=await resolveToken({token:inputToken,getAuthToken});const options={method,headers:{"Authorization":bearer(token)}};if(body!==undefined){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body);}const response=await fetchImpl(`${apiBase()}/api/movie-mentor/commercial${path}`,options);const payload=await json(response);if(!response.ok||payload?.success!==true)throw error(clean(payload?.code)||"MOVIE_MENTOR_COMMERCIAL_REQUEST_FAILED",clean(payload?.message)||"Movie Mentor could not safely complete that commercial request.",{status:response.status});return payload;}
async function listMovieMentorCommercialPackages({token,getAuthToken,fetchImpl}={}){const payload=await request("/packages",{token,getAuthToken,fetchImpl});if(!Array.isArray(payload?.packages))throw error("MOVIE_MENTOR_COMMERCIAL_PACKAGE_CATALOGUE_INVALID","Movie Mentor did not return an authorized package catalogue.");return payload.packages;}
async function createMovieMentorPurchaseIntent({packageId,token,getAuthToken,fetchImpl}={}){const selected=clean(packageId);if(!selected)throw error("MOVIE_MENTOR_COMMERCIAL_PACKAGE_REQUIRED","Choose a Movie Mentor package first.");const payload=await request("/purchase-intents",{method:"POST",body:{packageId:selected},token,getAuthToken,fetchImpl});const intent=payload?.intent;const commercialIntentId=clean(intent?.commercialIntentId);if(!commercialIntentId)throw error("MOVIE_MENTOR_COMMERCIAL_INTENT_INVALID","Movie Mentor did not return a durable commercial intent.");return{...intent,commercialIntentId};}
async function createMovieMentorCheckout({commercialIntentId,token,getAuthToken,fetchImpl}={}){const id=clean(commercialIntentId);if(!id)throw error("MOVIE_MENTOR_COMMERCIAL_INTENT_REQUIRED","A durable Movie Mentor commercial intent is required before checkout.");const payload=await request("/checkout",{method:"POST",body:{commercialIntentId:id},token,getAuthToken,fetchImpl});const checkout=payload?.checkout;const checkoutUrl=clean(checkout?.checkoutUrl);if(!checkoutUrl)throw error("MOVIE_MENTOR_COMMERCIAL_CHECKOUT_INVALID","Movie Mentor did not return an authorized checkout destination.");return{...checkout,checkoutUrl};}
async function beginMovieMentorPurchase({packageId,token,getAuthToken,fetchImpl,navigate=(url)=>globalThis?.location?.assign?.(url)}={}){const authToken=await resolveToken({token,getAuthToken});const intent=await createMovieMentorPurchaseIntent({packageId,token:authToken,fetchImpl});const checkout=await createMovieMentorCheckout({commercialIntentId:intent.commercialIntentId,token:authToken,fetchImpl});if(typeof navigate!=="function")throw error("MOVIE_MENTOR_COMMERCIAL_NAVIGATION_UNAVAILABLE","Checkout is authorized but this client cannot navigate to the provider.");navigate(checkout.checkoutUrl);return{intent,checkout};}
export{MOVIE_MENTOR_COMMERCIAL_CLIENT_VERSION,resolveToken,listMovieMentorCommercialPackages,createMovieMentorPurchaseIntent,createMovieMentorCheckout,beginMovieMentorPurchase};
export default beginMovieMentorPurchase;
