import React,{useState}from"react";
import{beginMovieMentorPurchase}from"./MovieMentorCommercialClient.js";

function clean(v){return typeof v==="string"?v.trim():"";}
function money(amountMinor,currency){try{return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(amountMinor/100);}catch{return `${currency} ${(amountMinor/100).toFixed(2)}`;}}

export default function MovieMentorCommercialSurface({packages=[],getAuthToken,onCheckoutStart,onCheckoutError,title="Continue creating with Movie Mentor"}){
 const [busy,setBusy]=useState(null),[message,setMessage]=useState("");
 const safePackages=Array.isArray(packages)?packages.filter(p=>clean(p?.packageId)&&Number.isSafeInteger(p?.amountMinor)&&p.amountMinor>0&&clean(p?.currency)&&Number.isSafeInteger(p?.units)&&p.units>0):[];
 async function buy(pkg){if(busy)return;setBusy(pkg.packageId);setMessage("");try{if(typeof getAuthToken!=="function")throw Object.assign(new Error("Sign in before starting checkout."),{code:"MOVIE_MENTOR_COMMERCIAL_AUTH_REQUIRED"});const token=await getAuthToken();onCheckoutStart?.({packageId:pkg.packageId});await beginMovieMentorPurchase({packageId:pkg.packageId,token});}catch(error){setMessage(error?.message||"Movie Mentor could not safely start checkout. Please try again.");onCheckoutError?.(error);}finally{setBusy(null);}}
 if(!safePackages.length)return null;
 return <section aria-label="Movie Mentor packages" style={styles.shell}><div style={styles.eyebrow}>MOVIE MENTOR ACCESS</div><h3 style={styles.title}>{title}</h3><p style={styles.copy}>Choose the amount of Movie Mentor creation you want. Secure checkout opens only after Movie Mentor creates your server-authorized purchase.</p><div style={styles.grid}>{safePackages.map(pkg=><article key={pkg.packageId} style={styles.card}><strong style={styles.units}>{pkg.units} creation units</strong><span style={styles.price}>{money(pkg.amountMinor,pkg.currency)}</span><button type="button" disabled={Boolean(busy)} onClick={()=>buy(pkg)} style={{...styles.button,...(busy?styles.buttonDisabled:{})}}>{busy===pkg.packageId?"Opening secure checkout…":"Choose package"}</button></article>)}</div>{message&&<div role="alert" style={styles.error}>{message}</div>}<p style={styles.note}>Payment is confirmed by the payment provider directly to Movie Mentor. Returning to this page never grants credits by itself.</p></section>;
}
const styles={shell:{border:"1px solid rgba(255,255,255,.12)",borderRadius:18,padding:18,background:"rgba(255,255,255,.035)"},eyebrow:{fontSize:11,fontWeight:800,letterSpacing:".14em",opacity:.7},title:{margin:"6px 0 6px",fontSize:20},copy:{margin:"0 0 14px",lineHeight:1.5,opacity:.82},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10},card:{display:"flex",flexDirection:"column",gap:8,padding:14,borderRadius:14,border:"1px solid rgba(255,255,255,.1)"},units:{fontSize:14},price:{fontSize:22,fontWeight:850},button:{border:0,borderRadius:12,padding:"11px 12px",fontWeight:800,cursor:"pointer"},buttonDisabled:{opacity:.55,cursor:"wait"},error:{marginTop:12,padding:10,borderRadius:10,border:"1px solid currentColor"},note:{margin:"12px 0 0",fontSize:12,lineHeight:1.45,opacity:.65}};
