import createResponseGenerator from "./ResponseGenerator.js";
import createMovieSemanticResponseProvider from "./MovieSemanticResponseProvider.js";
import createMovieMentorAgentPlan from "./MovieMentorAgentOrchestrator.js";
import createMovieSpecialistAgentProvider from "./MovieSpecialistAgentProvider.js";
import createMovieMentorSynthesisProvider from "./MovieMentorSynthesisProvider.js";

const MOVIE_MENTOR_RESPONSE_SERVICE_VERSION="1.6.0";
const semanticResponseProvider=createMovieSemanticResponseProvider(); const specialistAgentProvider=createMovieSpecialistAgentProvider(); const mentorSynthesisProvider=createMovieMentorSynthesisProvider(); const responseGenerator=createResponseGenerator({responseProvider:semanticResponseProvider});
function cleanString(v){return typeof v==="string"?v.trim():"";} function asArray(v){return Array.isArray(v)?v:[];} function cloneValue(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function getStructuredMovieIntelligence(result){const s=result?.response?.structured;const m=result?.provider?.metadata;const c=s?.movieJourneyIntelligence||s?.journeyIntelligence||s?.creatorJourneyIntelligence||m?.movieJourneyIntelligence||m?.journeyIntelligence||null;return c&&typeof c==="object"?c:null;}
function getAdaptiveAction(r){return cleanString(r?.adaptivePlan?.primaryAction?.action||r?.blueprint?.action||"");} function getQuestionPolicy(r){return cleanString(r?.adaptivePlan?.behaviour?.questionPolicy?.policy||r?.adaptivePlan?.behaviour?.questionPolicy||"");} function adaptivePlanRequiresMeaningClarification(r){return getAdaptiveAction(r).includes("clarify")||r?.diagnostics?.contextSnapshot?.creatorAppearsConfused===true;}
function createSafeMovieJourneyIntelligence(result,request={}){const p=getStructuredMovieIntelligence(result);if(p){const clarificationNeeded=asArray(p.clarificationNeeded);const material=clarificationNeeded.some(i=>i?.material!==false);return {understoodContext:asArray(p.understoodContext),provisionalContext:asArray(p.provisionalContext),unresolvedContext:asArray(p.unresolvedContext),clarificationNeeded,readyToAdvance:p.readyToAdvance===true&&!material,recommendedStageId:cleanString(p.recommendedStageId)||"story-direction",recommendedTaskId:cleanString(p.recommendedTaskId)||null,nextAction:p.nextAction&&typeof p.nextAction==="object"?cloneValue(p.nextAction):null,resumeNote:cleanString(p.resumeNote)||null,metadata:{...(p.metadata||{}),source:"response-generator-provider-intelligence",serviceVersion:MOVIE_MENTOR_RESPONSE_SERVICE_VERSION,semanticInterpretationAvailable:true,semanticInterpretationApplied:true,materialClarificationOverridesAdvance:true}};}const originalIdea=cleanString(request.idea);const clarificationRequired=adaptivePlanRequiresMeaningClarification(result);return {understoodContext:[],provisionalContext:[],unresolvedContext:[],clarificationNeeded:clarificationRequired?[{key:"movie.idea.meaning",expression:null,question:"I want to make sure I understand what you mean before we build on it. Can you explain that part a little further?",reason:"Adaptive Mentor indicates that meaning requires clarification before the movie journey advances.",material:true}]:[],readyToAdvance:false,recommendedStageId:"story-direction",recommendedTaskId:null,nextAction:null,resumeNote:originalIdea?"The creator's original idea is preserved. Remain in the Idea stage until semantic Mentor intelligence explicitly confirms that the meaning is understood well enough to advance.":null,metadata:{source:"adaptive-mentor-safe-fallback",serviceVersion:MOVIE_MENTOR_RESPONSE_SERVICE_VERSION,semanticInterpretationAvailable:false,semanticInterpretationApplied:false,adaptiveAction:getAdaptiveAction(result)||null,questionPolicy:getQuestionPolicy(result)||null,blockedFromAdvancingWithoutSemanticIntelligence:true}};}
function createSpecialistAgentPlan({request={},context={},movieJourneyIntelligence={}}={}){return createMovieMentorAgentPlan({stageId:cleanString(movieJourneyIntelligence.recommendedStageId)||cleanString(context.activeStage)||"idea",taskId:cleanString(movieJourneyIntelligence.recommendedTaskId)||cleanString(context.nextTask)||null,creatorMessage:cleanString(request.idea),semanticIntelligence:movieJourneyIntelligence,creatorConfirmedContext:cloneValue(context.creatorConfirmedContext||[]),projectJourney:cloneValue(context.projectJourney||null)});}
function createMentorSynthesisContext({specialistAgentPlan,specialistExecution,movieJourneyIntelligence}={}){const blocked=asArray(movieJourneyIntelligence?.clarificationNeeded).some(i=>i?.material!==false);return {source:"movie-mentor-specialist-orchestration",selectedAgents:asArray(specialistAgentPlan?.selectedAgents),contributions:asArray(specialistExecution?.contributions),failures:asArray(specialistExecution?.failures),skipped:asArray(specialistExecution?.skipped),creativeSynthesisBlockedByMaterialClarification:blocked,rules:{authorityOrder:["creator-confirmed-truth","validated-semantic-intelligence","specialist-contributions"],creatorTruthDominates:true,validatedSemanticsOutrankSpecialists:true,contributionsAreProvisional:true,mentorMaySelectCombineDeferOrIgnore:true,specialistsMayNotSpeakDirectly:true,specialistsMayNotAdvanceJourney:true,specialistContentBecomesCanonicalJourneyTruth:false,mentorMustSynthesize:true}};}
async function executeSpecialistAgentPlanSafely(plan){if(!plan||plan.status==="blocked-by-clarification"||asArray(plan.workOrders).length===0)return {status:plan?.status==="blocked-by-clarification"?"blocked-by-clarification":"skipped",contributions:[],failures:[],skipped:[],metadata:{reason:"no-executable-specialist-work"}};try{return await specialistAgentProvider.executePlan(plan);}catch(error){return {status:"failed-safe",contributions:[],skipped:[],failures:[{code:error?.code||"MOVIE_SPECIALIST_GATEWAY_FAILED",message:error instanceof Error?error.message:"Specialist gateway failed."}],metadata:{providerVersion:specialistAgentProvider.version,failedSafe:true}};}}
async function synthesizeMentorResponseSafely({request,context,result,movieJourneyIntelligence,mentorSynthesisContext}={}){const originalText=cleanString(result?.response?.text);if(mentorSynthesisContext?.creativeSynthesisBlockedByMaterialClarification)return {status:"blocked-by-clarification",text:originalText,decision:null,metadata:{reason:"material-semantic-clarification-required"}};if(asArray(mentorSynthesisContext?.contributions).length===0)return {status:"skipped",text:originalText,decision:null,metadata:{reason:"no-specialist-contributions"}};try{const synthesis=await mentorSynthesisProvider.synthesize({creatorMessage:cleanString(request?.idea),creatorConfirmedContext:cloneValue(context?.creatorConfirmedContext||[]),semanticIntelligence:cloneValue(movieJourneyIntelligence||{}),semanticMentorDraft:originalText,contributions:cloneValue(mentorSynthesisContext.contributions),responseBlueprint:cloneValue(result?.blueprint||null),communicationPlan:cloneValue(result?.communicationPlan||null)});return {status:"completed",text:cleanString(synthesis?.text)||originalText,decision:cloneValue(synthesis?.synthesisDecision||null),authority:cloneValue(synthesis?.authority||null),metadata:cloneValue(synthesis?.metadata||{})};}catch(error){return {status:"failed-safe",text:originalText,decision:null,metadata:{failedSafe:true,code:error?.code||"MOVIE_MENTOR_SYNTHESIS_FAILED",message:error instanceof Error?error.message:"Mentor synthesis failed."}};}}
async function generateMovieMentorResponse(request={}){const idea=cleanString(request.idea);const movieJourneyContext=request.movieJourneyContext&&typeof request.movieJourneyContext==="object"?request.movieJourneyContext:{};const context={...cloneValue(movieJourneyContext),creatorType:request.creatorType||movieJourneyContext.creatorType||"video",creatorJourney:request.creatorJourney||movieJourneyContext.creatorJourney||"guide",conversationMode:request.creatorMode||movieJourneyContext.conversationMode||"ai-movie",activeIdea:idea||movieJourneyContext.activeIdea||null,projectJourney:cloneValue(request.projectJourneySnapshot)||cloneValue(movieJourneyContext.projectJourney)||null,projectJourneyOrientation:cloneValue(request.projectJourneyOrientation)||cloneValue(movieJourneyContext.projectJourneyOrientation)||null};
 const result=await responseGenerator.generateResponse({message:idea,context,options:{includeDiagnostics:true,includeSpecialistPlans:false,includeBlueprint:true,includeCommunicationPlan:true,metadata:{creatorMode:request.creatorMode||"ai-movie",movieJourneyIntelligenceRequested:true,semanticProvider:"movie-mentor-semantic-gateway",specialistAgentOrchestrationRequested:true,movieJourneyIntelligenceContract:{fields:["understoodContext","provisionalContext","unresolvedContext","clarificationNeeded","readyToAdvance","recommendedStageId","recommendedTaskId","nextAction","resumeNote"],rule:"Return structured movie journey intelligence only when meaning is supported. Never invent creator decisions; material ambiguity requires clarification. Advancement requires explicit semantic intelligence, not merely a deterministic progression signal."}}}});
 const movieJourneyIntelligence=createSafeMovieJourneyIntelligence(result,request);const specialistAgentPlan=createSpecialistAgentPlan({request,context,movieJourneyIntelligence});const specialistExecution=await executeSpecialistAgentPlanSafely(specialistAgentPlan);const mentorSynthesisContext=createMentorSynthesisContext({specialistAgentPlan,specialistExecution,movieJourneyIntelligence});const mentorSynthesis=await synthesizeMentorResponseSafely({request,context,result,movieJourneyIntelligence,mentorSynthesisContext});const text=cleanString(mentorSynthesis.text)||cleanString(result?.response?.text)||idea;
 return {...result,response:{...(result?.response||{}),text},prompt:text,content:text,preview:text,movieJourneyIntelligence,specialistAgentPlan,specialistExecution,mentorSynthesisContext,mentorSynthesis,metadata:{...(result?.metadata||{}),movieJourneyIntelligence,specialistAgentPlan,specialistExecution,mentorSynthesisContext,mentorSynthesis,movieMentorResponseServiceVersion:MOVIE_MENTOR_RESPONSE_SERVICE_VERSION,semanticResponseProviderVersion:semanticResponseProvider.version||null,specialistAgentProviderVersion:specialistAgentProvider.version||null,mentorSynthesisProviderVersion:mentorSynthesisProvider.version||null,specialistAgentsAreAdvisoryOnly:true,specialistAgentsMayAdvanceJourney:false,specialistAgentsSpeakThroughMentorOnly:true,specialistContentBecomesCanonicalJourneyTruth:false}};}
export {MOVIE_MENTOR_RESPONSE_SERVICE_VERSION,createSafeMovieJourneyIntelligence,createSpecialistAgentPlan,createMentorSynthesisContext,executeSpecialistAgentPlanSafely,synthesizeMentorResponseSafely,generateMovieMentorResponse}; export default generateMovieMentorResponse;
