import React,{useEffect,useState}from"react";
import{beginMovieMentorPurchase,listMovieMentorCommercialPackages}from"./MovieMentorCommercialClient.js";
import{getMovieMentorCreatorAuthState,subscribeMovieMentorCreatorAuthState}from"./MovieMentorCreatorAuthenticationTransport.js";

function clean(v){return typeof v==="string"?v.trim():"";}
function money(amountMinor,currency){try{return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(amountMinor/100);}catch{return `${currency} ${(amountMinor/100).toFixed(2)}`;}}
function safePackage(p){return clean(p?.packageId)&&Number.isSafeInteger(p?.amountMinor)&&p.amountMinor>0&&clean(p?.currency)&&Number.isSafeInteger(p?.units)&&p.units>0;}
function authReady(state){return state?.isLoaded===true&&state?.isSignedIn===true&&typeof state?.getToken==="function";}

export default function MovieMentorCommercialSurface({onCheckoutStart,onCheckoutError,title="Continue creating with Movie Mentor"}){
 const [packages,setPackages]=useState([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(null),[message,setMessage]=useState("");
 const [authState,setAuthState]=useState(()=>getMovieMentorCreatorAuthState());
 useEffect(()=>subscribeMovieMentorCreatorAuthState(setAuthState),[]);
 useEffect(()=>{let live=true;if(!authReady(authState)){setPackages([]);setLoading(false);setMessage(authState?.isLoaded===true&&authState?.isSignedIn!==true?"Sign in to view Movie Mentor access options.":"");return()=>{live=false;};}(async()=>{setLoading(true);setMessage("");try{const catalogue=await listMovieMentorCommercialPackages();if(live)setPackages(Array.isArray(catalogue)?catalogue.filter(safePackage):[]);}catch(error){if(live){setPackages([]);setMessage(error?.message||"Movie Mentor packages are unavailable right now.");}}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[authState]);
 async function buy(pkg){if(busy||!authReady(getMovieMentorCreatorAuthState()))return;setBusy(pkg.packageId);setMessage("");try{onCheckoutStart?.({packageId:pkg.packageId});await beginMovieMentorPurchase({packageId:pkg.packageId});}catch(error){setMessage(error?.message||"Movie Mentor could not safely start checkout. Please try again.");onCheckoutError?.(error);}finally{setBusy(null);}}
 if(loading)return <section aria-label="Movie Mentor packages" style={styles.shell}><p style={styles.copy}>Loading your Movie Mentor access options…</p></section>;
 if(!packages.length&&!message)return null;
 return <section aria-label="Movie Mentor packages" style={styles.shell}><div style={styles.eyebrow}>MOVIE MENTOR ACCESS</div><h3 style={styles.title}>{title}</h3>{packages.length>0&&<><p style={styles.copy}>Choose the amount of Movie Mentor creation you want. These options come directly from Movie Mentor's server-authorized commercial policy.</p><div style={styles.grid}>{packages.map(pkg=><article key={pkg.packageId} style={styles.card}><strong style={styles.units}>{pkg.units} creation units</strong><span style={styles.price}>{money(pkg.amountMinor,pkg.currency)}</span><button type="button" disabled={Boolean(busy)} onClick={()=>buy(pkg)} style={{...styles.button,...(busy?styles.buttonDisabled:{})}}>{busy===pkg.packageId?"Opening secure checkout…":"Choose package"}</button></article>)}</div></>}{message&&<div role="alert" style={styles.error}>{message}</div>}<p style={styles.note}>Payment is confirmed by the payment provider directly to Movie Mentor. Returning to this page never grants credits by itself.</p></section>;
}
const styles={shell:{border:"1px solid rgba(20,24,32,.10)",borderRadius:18,padding:18,background:"#fff",boxShadow:"0 8px 24px rgba(17,24,39,.05)"},eyebrow:{fontSize:11,fontWeight:800,letterSpacing:".14em",opacity:.7},title:{margin:"6px 0 6px",fontSize:20},copy:{margin:"0 0 14px",lineHeight:1.5,opacity:.82},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10},card:{display:"flex",flexDirection:"column",gap:8,padding:14,borderRadius:14,border:"1px solid rgba(20,24,32,.1)"},units:{fontSize:14},price:{fontSize:22,fontWeight:850},button:{border:0,borderRadius:12,padding:"11px 12px",fontWeight:800,cursor:"pointer"},buttonDisabled:{opacity:.55,cursor:"wait"},error:{marginTop:12,padding:10,borderRadius:10,border:"1px solid currentColor"},note:{margin:"12px 0 0",fontSize:12,lineHeight:1.45,opacity:.65}};
