import { getMovieMentorCreatorAuthToken } from "./MovieMentorCreatorAuthenticationTransport.js";

const MOVIE_MENTOR_DURABLE_STATE_SYNC_VERSION="1.2.1";
const REVISION_KEY_PREFIX="iband.movie-mentor.durable-revision";
const STATUS_KEY_PREFIX="iband.movie-mentor.durable-sync-status";
const CREATOR_MEMORY_KEY_PREFIX="iband.creator-memory";
const pendingByIdentity=new Map();
const inFlightByIdentity=new Map();
let bridgeInstalled=false;
function s(v){return typeof v==="string"?v.trim():"";}
function clone(v){if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch{return v;}}
function apiBase(){return s(import.meta?.env?.VITE_API_BASE_URL||import.meta?.env?.VITE_BACKEND_URL||"").replace(/\/$/,"");}
function identityKey(projectId,creatorSessionId){return s(projectId)||`session:${s(creatorSessionId)}`;}
function revisionKey(projectId,creatorSessionId){return `${REVISION_KEY_PREFIX}:${identityKey(projectId,creatorSessionId)}`;}
function statusKey(projectId,creatorSessionId){return `${STATUS_KEY_PREFIX}:${identityKey(projectId,creatorSessionId)}`;}
function getExpectedRevision({projectId,creatorSessionId,storage=globalThis?.localStorage}={}){try{const value=Number(storage?.getItem?.(revisionKey(projectId,creatorSessionId)));return Number.isSafeInteger(value)&&value>=0?value:0;}catch{return 0;}}
function rememberRevision({projectId,creatorSessionId,revision,storage=globalThis?.localStorage}={}){if(!Number.isSafeInteger(revision)||revision<0)return;try{storage?.setItem?.(revisionKey(projectId,creatorSessionId),String(revision));}catch{}}
function writeStatus({projectId,creatorSessionId,status,storage=globalThis?.localStorage,error=null,revision=null}={}){const value={status,projectId:s(projectId)||null,creatorSessionId:s(creatorSessionId)||null,revision:Number.isSafeInteger(revision)?revision:null,error:error?{code:s(error.code)||null,message:s(error.message)||String(error)}:null,updatedAt:new Date().toISOString()};try{storage?.setItem?.(statusKey(projectId,creatorSessionId),JSON.stringify(value));}catch{}return value;}
function getDurableSyncStatus({projectId,creatorSessionId,storage=globalThis?.localStorage}={}){try{const raw=storage?.getItem?.(statusKey(projectId,creatorSessionId));return raw?JSON.parse(raw):null;}catch{return null;}}
function projectMemoryContext(memoryState,projectId){const pid=s(projectId);const relevant=(items=[])=>items.filter(item=>{const direct=s(item?.projectId||item?.relatedProjectId||item?.metadata?.projectId);const related=Array.isArray(item?.relatedProjectIds)?item.relatedProjectIds.map(s):[];return !direct&&!related.length||direct===pid||related.includes(pid);});return{creatorProfile:clone(memoryState?.creatorProfile||null),ideas:clone(relevant(memoryState?.ideas||[])),projectMemories:clone(relevant(memoryState?.projectMemories||[])),sessionHandoffs:clone(relevant(memoryState?.sessionHandoffs||[])),conversations:clone(relevant(memoryState?.conversations||[])),observations:clone(relevant(memoryState?.observations||[])),patterns:clone(relevant(memoryState?.patterns||[])),milestones:clone(relevant(memoryState?.milestones||[])),reflections:clone(relevant(memoryState?.reflections||[])),deferredMemories:clone(relevant(memoryState?.deferredMemories||[]))};}
function creatorConfirmedContext(memoryState,projectId){const pid=s(projectId);const project=(memoryState?.projects||[]).find(p=>s(p?.id||p?.projectId)===pid)||null;return[{key:"creatorProfile",value:clone(memoryState?.creatorProfile||null),source:"creator-memory",certainty:"confirmed"},{key:"project",value:clone(project),source:"creator-memory",certainty:"confirmed"}].filter(x=>x.value!==null);}
function syncIdentityFromMemory(memoryState={}){const projectId=s(memoryState?.journey?.activeProjectId)||s((memoryState?.projects||[]).find(p=>p?.active===true)?.id)||null;const creatorSessionId=!projectId?s(memoryState?.creatorProfile?.id)||null:null;return{projectId,creatorSessionId};}
async function syncMovieMentorDurableState({projectId,creatorSessionId=null,memoryState,source="creator-memory",fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,getAuthToken=getMovieMentorCreatorAuthToken}={}){const pid=s(projectId),sid=s(creatorSessionId);if(!pid&&!sid)throw new Error("Movie Mentor durable sync requires projectId or creatorSessionId.");if(!memoryState||typeof memoryState!=="object")throw new Error("Movie Mentor durable sync requires CreatorMemory state.");if(typeof fetchImpl!=="function")throw new Error("Movie Mentor durable sync requires fetch.");if(typeof getAuthToken!=="function")throw Object.assign(new Error("Movie Mentor durable sync requires creator authentication transport."),{code:"MOVIE_MENTOR_DURABLE_STATE_SYNC_AUTH_REQUIRED"});const expectedRevision=getExpectedRevision({projectId:pid,creatorSessionId:sid,storage});writeStatus({projectId:pid,creatorSessionId:sid,status:"syncing",storage,revision:expectedRevision});let response;try{const token=s(await getAuthToken());if(!token)throw Object.assign(new Error("Movie Mentor durable sync requires a current creator authentication token."),{code:"MOVIE_MENTOR_DURABLE_STATE_SYNC_AUTH_REQUIRED"});response=await fetchImpl(`${apiBase()}/api/movie-mentor/state/sync`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify({projectId:pid||null,creatorSessionId:sid||null,source,expectedRevision,state:{creatorConfirmedContext:creatorConfirmedContext(memoryState,pid),projectJourney:clone(memoryState?.journey||null),memoryContext:projectMemoryContext(memoryState,pid)}})});}catch(cause){const error=cause instanceof Error?cause:new Error(String(cause));if(!error.code)error.code="MOVIE_MENTOR_DURABLE_STATE_SYNC_NETWORK_FAILED";writeStatus({projectId:pid,creatorSessionId:sid,status:"retry-pending",storage,error,revision:expectedRevision});throw error;}const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload?.message||"Movie Mentor durable state sync failed.");error.code=payload?.code||"MOVIE_MENTOR_DURABLE_STATE_SYNC_FAILED";error.status=response.status;writeStatus({projectId:pid,creatorSessionId:sid,status:error.code==="MOVIE_MENTOR_CREATOR_STATE_REVISION_CONFLICT"?"conflict-pending":"retry-pending",storage,error,revision:expectedRevision});throw error;}rememberRevision({projectId:pid,creatorSessionId:sid,revision:payload?.state?.revision,storage});writeStatus({projectId:pid,creatorSessionId:sid,status:"acknowledged",storage,revision:payload?.state?.revision});return payload;}
async function drainIdentity(key,{fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,getAuthToken=getMovieMentorCreatorAuthToken}={}){if(inFlightByIdentity.has(key))return inFlightByIdentity.get(key);const run=(async()=>{while(pendingByIdentity.has(key)){const job=pendingByIdentity.get(key);pendingByIdentity.delete(key);try{await syncMovieMentorDurableState({...job,fetchImpl,storage,getAuthToken});}catch(error){pendingByIdentity.set(key,job);break;}}})().finally(()=>inFlightByIdentity.delete(key));inFlightByIdentity.set(key,run);return run;}
function enqueueMovieMentorDurableStateSync({memoryState,source="creator-memory",fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,getAuthToken=getMovieMentorCreatorAuthToken}={}){if(!memoryState||typeof memoryState!=="object")return null;const identity=syncIdentityFromMemory(memoryState);if(!identity.projectId&&!identity.creatorSessionId)return null;const key=identityKey(identity.projectId,identity.creatorSessionId);pendingByIdentity.set(key,{...identity,memoryState:clone(memoryState),source});writeStatus({...identity,status:"queued",storage,revision:getExpectedRevision({...identity,storage})});queueMicrotask(()=>void drainIdentity(key,{fetchImpl,storage,getAuthToken}));return key;}
async function flushMovieMentorDurableStateSync({projectId,creatorSessionId,fetchImpl=globalThis?.fetch,storage=globalThis?.localStorage,getAuthToken=getMovieMentorCreatorAuthToken}={}){const key=identityKey(projectId,creatorSessionId);await drainIdentity(key,{fetchImpl,storage,getAuthToken});return getDurableSyncStatus({projectId,creatorSessionId,storage});}
function installCreatorMemoryDurableSyncBridge({storage=globalThis?.localStorage,fetchImpl=globalThis?.fetch,getAuthToken=getMovieMentorCreatorAuthToken}={}){if(bridgeInstalled||typeof Storage==="undefined"||!storage)return false;const original=Storage.prototype.setItem;if(typeof original!=="function")return false;Storage.prototype.setItem=function(key,value){const result=original.call(this,key,value);try{if(this===storage&&s(key).startsWith(CREATOR_MEMORY_KEY_PREFIX)){const state=JSON.parse(value);enqueueMovieMentorDurableStateSync({memoryState:state,fetchImpl,storage,getAuthToken});}}catch{}return result;};bridgeInstalled=true;try{for(let i=0;i<storage.length;i+=1){const key=storage.key(i);if(s(key).startsWith(CREATOR_MEMORY_KEY_PREFIX)){const raw=storage.getItem(key);if(raw){try{enqueueMovieMentorDurableStateSync({memoryState:JSON.parse(raw),fetchImpl,storage,getAuthToken});}catch{}}}}}catch{}return true;}
export{MOVIE_MENTOR_DURABLE_STATE_SYNC_VERSION,getExpectedRevision,rememberRevision,getDurableSyncStatus,projectMemoryContext,creatorConfirmedContext,syncIdentityFromMemory,syncMovieMentorDurableState,enqueueMovieMentorDurableStateSync,flushMovieMentorDurableStateSync,installCreatorMemoryDurableSyncBridge};
export default syncMovieMentorDurableState;
