name: CI (Frontend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # no cache here (no lockfile yet)

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build (noop for now)
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script; skipping"
          fi

      - name: List files (sanity)
        run: ls -la