name: CI (Frontend)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # no cache: we don't have a package-lock.json yet

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build (noop for static site)
        run: npm run build

      - name: Verify "serve" is available
        run: npx serve --version